### ISSUE TITLE
appcompat не работает

### ISSUE THREAD

**Issue by AnastasiaSulyagina** [CSC-MobDev-2016/lesson4#1]
Добрый день!
Не подскажете ли Вы случайно, почему могут быть проблемы с appcompat?
Каждый раз, когда клоню к себе репозиторий с дз, ничего не резолвится, приходится подключать ее отдельно, но то можно пережить. В этот раз никак не грузятся ресурсы, сделала все, что советуют в интернетах - ничего не помогает. Не могу ни дебажить, ни запускать - ничего.

![2016-03-19 15 10 06](https://cloud.githubusercontent.com/assets/6882628/13898768/de843876-edf5-11e5-92f3-29ac02d025c3.png)

Спасибо,
Настя

**Comment by AnastasiaSulyagina** [comment]
Перепробовала все возможные комбинации из версий сдк - не помогает

**Comment by thevery** [comment]
Support repository через sdk manager установили?

**Comment by thevery** [comment]
А, ну вроде должен быть. А из консоли собирается проект?

**Comment by thevery** [comment]
Ну и хорошо бы обновить студию и sdk/platrom tools, если вдруг старые.

**Comment by AnastasiaSulyagina** [comment]
Да, из sdk установлено абсолютно все после андроида 4.0, все tools и все extras
После предыдущего занятия снесла идею и сдк и поставила заново
Из консоли не пробовала

**Comment by thevery** [comment]
Вообще у меня набор библиотек сильно различается:
![2016-03-19 18-15-05 readme md - lesson4 - git csc16 lesson4 - android studio 2 1 preview 3](https://cloud.githubusercontent.com/assets/99576/13899412/92844f02-edfe-11e5-8bd4-19c068500685.png)

**Comment by AnastasiaSulyagina** [comment]
Но она там есть
![2016-03-19 18 18 19](https://cloud.githubusercontent.com/assets/6882628/13899427/5b294752-ee07-11e5-8207-954fc23c8607.png)

В bash.profile:
export ANDROID_HOME="$/Users/anastasia/Development/TOOLS/android-sdk-macosx:$ANDROID_HOME"
export PATH="$/Users/anastasia/Development/TOOLS/android-sdk-macosx/platform-tools:$PATH"
export PATH="$/Users/anastasia/Development/TOOLS/android-sdk-macosx/tools:$PATH"

Ваш набор похож на правду, но у меня всего этого нет

**Comment by thevery** [comment]
вижу лишний `$` как минимум

**Comment by thevery** [comment]
а вообще на мак удобнее всего ставить sdk через brew.sh, а в profile прописывать только `export ANDROID_HOME=/usr/local/opt/android-sdk` (PATH трогать не нужно)

**Comment by AnastasiaSulyagina** [comment]
Благодарю, сейчас попробую

**Comment by AnastasiaSulyagina** [comment]
А еще не подскажете, какой эмулятор лучше использовать?

**Comment by thevery** [comment]
genymotion

**Comment by AnastasiaSulyagina** [comment]
Спасибо

**Comment by thevery** [comment]
заработало в итоге?

**Comment by AnastasiaSulyagina** [comment]
Гружу сдк по новой, отпишусь когда проверю

**Comment by AnastasiaSulyagina** [comment]
Из командной строки сбилдилось, из идеи - нет, все те же ошибки.
Выглядят библиотеки теперь так
![2016-03-19 20 22 59](https://cloud.githubusercontent.com/assets/6882628/13900143/cda0fdfa-ee18-11e5-8804-a9e658adfb8a.png)
Но в библиотеках есть вот это

![2016-03-19 20 24 49](https://cloud.githubusercontent.com/assets/6882628/13900164/145c1ad6-ee19-11e5-9645-b3fa6f716faa.png)

**Comment by AnastasiaSulyagina** [comment]
5 раз перезапустила идею - сбилдилось. Спасибо
